global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'tasks-service'
    static_configs:
      - targets: ['host.docker.internal:8082']  # для Windows/Mac
        labels:
          service: 'tasks'
    metrics_path: /metrics
    scrape_interval: 5s

